import type { Metadata } from "next";
import { Lora } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '700'], // Adjust as needed
  variable: '--font-lora', // Optional CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.className}  antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
